### ISSUE TITLE
Cross not compatible with SELinux

### ISSUE THREAD

**Issue by Susurrus** [rust-embedded/cross#112]
I've been trying to debug our CI failures by running cross locally, but I've run into `Permission denied` error when doing so. I'm not really certain where to look to try and debug this issue, so I'm posting here. Any help figuring this out would be appreciated.

```
$ cross build --target aarch64-unknown-linux-gnu
Unable to find image 'japaric/aarch64-unknown-linux-gnu:v0.1.10' locally
Trying to pull repository docker.io/japaric/aarch64-unknown-linux-gnu ... 
sha256:7bd5365e6aec2cdcab009e59039117f3e8b5e25b089d28d30036a10739225fdc: Pulling from docker.io/japaric/aarch64-unknown-linux-gnu
30d541b48fc0: Pull complete 
8ecd7f80d390: Pull complete 
46ec9927bb81: Pull complete 
2e67a4d67b44: Pull complete 
7d9dd9155488: Pull complete 
08aa1b431028: Pull complete 
7d802a03e2fb: Pull complete 
a37098550b32: Pull complete 
031c3405b7a7: Pull complete 
Digest: sha256:7bd5365e6aec2cdcab009e59039117f3e8b5e25b089d28d30036a10739225fdc
Status: Downloaded newer image for docker.io/japaric/aarch64-unknown-linux-gnu:v0.1.10
sh: 1: cargo: Permission denied
```

**Comment by th0br0** [comment]
If you're running on an SELinux-enabled system, SELinux is probably at fault.
Try running it again after `sudo setenforce 0`.

**Comment by Susurrus** [comment]
Indeed, that was it. Fedora has SELinux on by default. The failure message here is confusing, it'd be nice if the invalid permissions could be detected and a clearer message could be provided. Don't know if that's for `cargo` or `cross` to address, however.

**Comment by thejpster** [comment]
I've just fallen across this one as well. Unfortunately I don't think disabling SELinux is ever a good solution - it's there for a reason!

**Comment by jamesmunns** [comment]
Duplicates https://github.com/japaric/cross/issues/185, there needs to be better documentation on what the requirements `cross` has for running on the host environment, which pretty much boils down to "you need to be able to `docker run` as the current user without selinux or sudo problems.

**Comment by thejpster** [comment]
SELinux isn't a 'problem', it's a security feature. Cross should support mounting volumes using the Z flag.

**Comment by jamesmunns** [comment]
@thejpster makes sense. Maybe another config flag for `CROSS_USE_ZFLAG` or something?

**Comment by jamesmunns** [comment]
Updated the title to better track the underlying issue. Thanks for the insight @thejpster!

**Comment by cyplo** [comment]
Using `Z` when mounting a volume on a system without SELinux just works as well, at least for my setup - would it be okay to just use it by default everywhere ?

**Comment by cyplo** [comment]
I went ahead and proposed a PR for this - #251 - feel free to close if it does not make sense though. 

Thanks !
