### ISSUE TITLE
build support for iOS targets

### ISSUE THREAD

**Issue by japaric** [rust-embedded/cross#148]
macOS can cross compile programs for iOS provided that the corresponding rust-std component is installed.

### What to do

- Automatically install the corresponding rust-std component when cross building / testing for iOS *on a macOS host*. The rust-std component should *not* be installed on Linux hosts.

- Update the README mentioning that iOS cross compilation is supported on macOS hosts.

**Comment by gnzlbg** [comment]
@malbarbo can the libc ci utilities for ios be reused here? I'd like to start testing stdsimd and slice_deque on ios as well.
