### ISSUE TITLE
Support arm-unknown-linux-gnueabihf target

### ISSUE THREAD

**Issue by gnzlbg** [rust-embedded/cross#155]
arm-unknown-linux-gnueabihf ~~and armv7-unknown-linux-gnueabihf~~ don't seem to be currently supported

**Comment by malbarbo** [comment]
armv7-unknown-linux-gnueabihf is supported.

**Comment by gnzlbg** [comment]
@malbarbo indeed, I'll send a PR to support that one

**Comment by lytedev** [comment]
Any particular reason this hasn't been merged?

**Comment by gnzlbg** [comment]
@lytedev there is a PR: #158 but it takes too long to build and needs to be updated to a pre-built toolchain. Feel free to pick it up.
