### ISSUE TITLE
Support for more *-musl targets

### ISSUE THREAD

**Issue by vorner** [rust-embedded/cross#168]
Hello

Would it be hard to add support for more *-musl targets where the *-gnu targets are already available? Eg `mips-unknown-linux-musl` or `aarch64-unknown-linux-musl`? Or is it just about modifying the `-gnu` target and adding compilation of musl into it?

The advantage of these targets is that they „just work“, even though they produce larger binaries. Therefore they are great for initial experiments before investing in supporting strange platforms (like -uclibc) or show-casing other colleagues how easy it is to cross-compile Rust for this or that device.

**Comment by jamesmunns** [comment]
@vorner makes sense! You should be able to add new targets to https://github.com/japaric/cross/tree/master/docker, let me know if you need any help adding them!

**Comment by vorner** [comment]
I'll try… but it'll take some time before I get to it, my local queue of things I'd like to fix or improve keeps growing.

**Comment by malbarbo** [comment]
This was fixed in https://github.com/rust-embedded/cross/pull/218.
