### ISSUE TITLE
x86_64-unknown-netbsd fails with error: Invalid arguments

### ISSUE THREAD

**Issue by gnzlbg** [rust-embedded/cross#179]
See: https://travis-ci.org/gnzlbg/slice_deque/jobs/337231953

```shell
Digest: sha256:f30dde2c05ff7281851789f3f6381c7f839bbdbab53ce56795742ad19a897bbd
Status: Downloaded newer image for japaric/x86_64-unknown-netbsd:v0.1.14
error: Invalid arguments.
```

**Comment by gnzlbg** [comment]
The following targets fail with the same error as well:

* x86_64-sun-solaris
* i686-unknown-freebsd
* x86_64-unknown-freebsd

**Comment by bgermann** [comment]
I think this was a nightly issue. With current nightly I cannot reproduce this issue anymore.

**Comment by Dylan-DPC** [comment]
@bgermann Hi

Just checked the repo and have noticed that this issue doesn't arise in the newer builds. So i'm closing this.
