### ISSUE TITLE
Release policy

### ISSUE THREAD

**Issue by Bobo1239** [rust-embedded/cross#216]
Now that the CI works again and new stuff is getting merged, I'm wondering what the release policy is going to be. AFAIKT only the master branch and tagged commits are published (see [here](https://github.com/rust-embedded/cross/blob/master/ci/after_success.sh)). IMO it'd make sense to release a new version after we've merged some of the less "risky" (in terms of breakage) PRs and then do a release to see if there are any problems before making bigger changes.

**Comment by Dylan-DPC** [comment]
@Bobo1239 yes agree with that. Most of the older PRs are adding support so trying to get those merged first. Once done we can prepare a release and test if everything is fine.

**Comment by whitfin** [comment]
I'm also interested in this; there has not been a release in over a year and there are 114 commits (currently) which are yet to be unreleased. It would be good, perhaps, to get a release out soon-ish to avoid things becoming overwhelming.

**Comment by reitermarkus** [comment]
Is there anything blocking a new release?

**Comment by rossmacarthur** [comment]
Hey I'm interested in this as well. I would like to use the latest Docker images. Is there anything that needs to be done before the release. I don't mind contributing.

**Comment by sanmai-NL** [comment]
New release: https://github.com/rust-embedded/cross/releases/tag/v0.1.15 .
