### ISSUE TITLE
Support non-Linux hosts

### ISSUE THREAD

**Issue by mcandre** [rust-embedded/cross#222]
Pls.

**Comment by Dylan-DPC** [comment]
Hi @mcandre 

Thanks for this issue. Is there any target you want to be supported? Are you open to submitting a PR? (we can guide you in that case). A list of targets will be beneficial.

**Comment by duncanfinney** [comment]
@Dylan-DPC I would be willing to submit a PR towards that if you could point me in the right direction. What about being a linux host makes it not work on mac?

**Comment by mcandre** [comment]
Actually, I suspect cross may already support non-Linux hosts, as Docker has decent support for macOS and Windows hosts! I just haven’t tested this out.

**Comment by mpapierski** [comment]
@mcandre unfortunately not luck (or maybe I'm doing something wrong) - apparently running `cross build --target mips-unknown-linux-gnu` doesn't event try to connect to docker running on my machine, and expects `mips-linux-gnu-gcc` on my machine. Anyone had luck with this?

**Comment by puddly** [comment]
@malbarbo I realized the same thing after a few long hours of fruitless debugging. Installing `cross` directly from Git (`cargo install --git https://github.com/rust-embedded/cross`) at least got it to start using a Docker image for `mips-unknown-linux-musl` (not `gnu`). That particular Docker image was private for some reason so I had to download it myself via the appropriate [`Dockerfile` in this repository](https://github.com/rust-embedded/cross/blob/master/docker/mips-unknown-linux-musl/Dockerfile) and point to an appropriately tagged local image via the `Cross.toml` file:

```toml
[target.mips-unknown-linux-musl]
image = "puddly:mips-openwrt-linux-musl-17.01.6"
```

**Comment by reitermarkus** [comment]
macOS and Windows hosts should now be working.
