### ISSUE TITLE
Update musl images

### ISSUE THREAD

**Issue by oblique** [rust-embedded/cross#234]
I was trying to build with `arm-unknown-linux-musleabi` and it was failing on `miniz-sys` compilation.
After I build the docker image from master branch I successfully build my project.

Since musl is not affected by https://github.com/rust-embedded/cross/pull/164#issuecomment-352188362 can you please update all musl images?

**Comment by Dylan-DPC** [comment]
@oblique Thanks for reporting this. The [build passes](https://travis-ci.org/rust-embedded/cross/jobs/463743067) for this architecture on CI. Can you post more details like your openssl version?

**Comment by oblique** [comment]
I don't use `openssl-sys`, but in any case my OpenSSL version: `1.1.1a  20 Nov 2018`.
Also if I see correctly from the logs, the `arm-unknown-linux-musleabihf` docker is actually build from git repo. The problem is the that DockerHub image is outdated.

Can you test the following with DockerHub image?

**cargo.toml**
```
[package]
name = "issue234"
version = "0.1.0"

[dependencies]
miniz-sys = "0.1.11"
```

**src/main.rs**
```
extern crate miniz_sys;
fn main() {
}
```

And I build with:
```
cross build --target arm-unknown-linux-musleabi
```

If I rebuild docker image from git repo, then everything works.

**Comment by epitstickpan** [comment]
The same problem is in #161

**Comment by DoumanAsh** [comment]
For these who will find need I published fresh build for [armv7-unknown-linux-musleabihf](https://hub.docker.com/r/douman/cross-armv7-unknown-linux-musleabihf) but without OpenSSL
Also surprisingly bigger than older one in japaric's

**Comment by reitermarkus** [comment]
I guess this should be working now that the new images are available on Docker Hub.
