### ISSUE TITLE
`armv7-unknown-linux-musleabihf`/`armv7-linux-musleabihf` hard-coded NEON support

### ISSUE THREAD

**Issue by briansmith** [rust-embedded/cross#252]
See https://github.com/rust-embedded/cross/blob/718a19cd68fb09428532d1317515fe7303692b47/docker/armv7-unknown-linux-musleabihf/Dockerfile#L30

According to https://github.com/rust-lang/rust/issues/47765 this is wrong.

See also https://github.com/rust-lang/rust/pull/56947 where new NEON-always-available target triples were added.

**Comment by jamesmunns** [comment]
Hey @briansmith, would you mind please removing this in a PR? I can kick of CI once you submit it.
