### ISSUE TITLE
bindgen seems to don't work inside cross containers

### ISSUE THREAD

**Issue by siscia** [rust-embedded/cross#257]
Hi,

I am trying to use cross to build a project which requires bindgen.

If I build the process directly from cross, bindgen is not able to find the needed library (namely libclang.so), however, if I start the same container and clone the repo inside, everything works just fine.

What can be the causes?
Open similar issue on bindgen: https://github.com/rust-lang/rust-bindgen/issues/1411#issuecomment-463666326

**Comment by jamesmunns** [comment]
@siscia this sounds a bit like a problem with your PATH variable. I'm guessing you might be using two different shells when using the container. I think by default docker uses the Dash shell, and you (or `cross`) might be using Bash instead.

Maybe in both cases, try adding the following to the procedure, and see if your outputs are different?

```sh
# print the current shell, one of these should work
echo $0
echo $SHELL

# print the current path variable
echo $PATH
```

**Comment by siscia** [comment]
Sorry, I wrote very badly.

So, if I execute 
```
cross build --target `....`
```
The build process start but it broke while it need the libclang libraries.

While if I run the same container, a git clone the repo, and I use the standard `cargo build` everything works.

I am not quite sure how to print the SHELL and the PATH variable while executing cross.

I agree that it may be the problem though...

**Comment by siscia** [comment]
Sorry, it seems that everything is just fixed using a different docker image.

**Comment by hug-dev** [comment]
Hi @siscia 
We have the exact same problem, using `bindgen` in our build script, it complains that it can not find `libclang.so`.

Just for reference: which Docker image were you using that worked? If you remember, I know it was some times ago 😃

**Comment by siscia** [comment]
Sorry guys, really no idea at all... :(

**Comment by hug-dev** [comment]
For future reference: we created a new `Dockerfile` with the following content to make `bindgen` work inside `cross`:
```
FROM rustembedded/cross:aarch64-unknown-linux-gnu-0.1.16

RUN apt-get update && \
    apt-get install -y clang libclang-dev libc6-dev-i386
```

**Comment by JayKickliter** [comment]
This is still a problem

**Comment by Nnubes256** [comment]
Very late to the party, but: some images (in my case, `arm-unknown-linux-gnueabi-0.2.1`) are still on Ubuntu 16.04.

In these cases, it seems the latest version is [3.8](https://packages.ubuntu.com/xenial/clang), which is incompatible with current versions of `bindgen`, as it requires [Clang 3.9](https://rust-lang.github.io/rust-bindgen/requirements.html#installing-clang-39). I've somewhat hastily constructed an image that fixes this by fetching from [LLVM's own repository](https://apt.llvm.org/):

```dockerfile
FROM rustembedded/cross:arm-unknown-linux-gnueabi-0.2.1

RUN dpkg --add-architecture arm && \
    apt-get update && \
    apt-get install -y apt-transport-https wget && \
    (wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -) && \
    printf "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-12 main\ndeb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-12 main" > /etc/apt/sources.list.d/backports.list && \
    apt-get update && \
    apt-get install -y llvm-3.9-dev libclang-3.9-dev clang-3.9 && \
    apt-get purge -y apt-transport-https wget
```

**Comment by timstokman** [comment]
To get bindgen working, all I did was use this docker image:

```
FROM rustembedded/cross:armv7-unknown-linux-gnueabihf-0.2.1

RUN apt-get update && apt-get install --assume-yes libclang-3.9-dev
```

Just libclang-3.9-dev is enough.

**Comment by Alexhuszagh** [comment]
This is now extensively documented on the [wiki](https://github.com/cross-rs/cross/wiki/FAQ#using-bindgen).
