### ISSUE TITLE
master is broken (again)

### ISSUE THREAD

**Issue by Disasm** [rust-embedded/cross#258]
The following targets fail to pass tests on master (see https://travis-ci.org/rust-embedded/cross/builds/491064271):
* [`powerpc64-unknown-linux-gnu`](https://travis-ci.org/rust-embedded/cross/jobs/491064283)
* [`sparc64-unknown-linux-gnu`](https://travis-ci.org/rust-embedded/cross/jobs/491064285)

Affected PRs: https://github.com/rust-embedded/cross/pull/255, https://github.com/rust-embedded/cross/pull/251

**Comment by Dylan-DPC** [comment]
Thanks

Fixed in https://github.com/rust-embedded/cross/pull/259/commits/108479e1fd859b4bf0ea5bf6d6a21fafe85d0f0c
