### ISSUE TITLE
arm-unknown-linux-gnueabihf missing from japaric Docker Hub account

### ISSUE THREAD

**Issue by ev-wilt** [rust-embedded/cross#261]
I noticed in PR #245 that support for arm-unknown-linux-gnueabihf was added, but it seems the Docker image wasn't added to the japaric account so any time I try to use arm-unknown-linux-gnueabihf as a target I get the following:

```
Unable to find image 'japaric/arm-unknown-linux-gnueabihf:latest' locally
docker: Error response from daemon: pull access denied for japaric/arm-unknown-linux-gnueabihf, repository does not exist or may require 'docker login'.
```

If this could be added I'd greatly appreciate it.

**Comment by bltavares** [comment]
@ev-wilt Meanwhile, I've built it locally and republished them on Docker Hub on this repo: https://hub.docker.com/r/rustreleaser/cross

Each tag is a platform, if you are still interested.

**Comment by lilianmoraru** [comment]
Still not working:
```
cross build --target arm-unknown-linux-gnueabihf
Unable to find image 'japaric/arm-unknown-linux-gnueabihf:latest' locally
docker: Error response from daemon: pull access denied for japaric/arm-unknown-linux-gnueabihf, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

**Comment by zeiv** [comment]
@lilianmoraru:

> Each tag is a platform, if you are still interested.

However, I am getting the `sh: 1: cargo: not found` on the images there.  Using the `arm-unknown-linux-gnueabihf` image.

**Comment by xoac** [comment]
Problem is also with: japaric/mips-unknown-linux-musl

```
docker pull japaric/mips-unknown-linux-musl
Using default tag: latest
Error response from daemon: pull access denied for japaric/mips-unknown-linux-musl, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by reitermarkus** [comment]
New images are now on https://hub.docker.com/r/rustembedded/cross.
