### ISSUE TITLE
Supporting relative path in Cargo.toml depends

### ISSUE THREAD

**Issue by TotalKrill** [rust-embedded/cross#277]
How would one do this, currently I am building the entire workspace, which makes it work, but then other tools doesn't work since they do not support workspaces it seems

**Comment by Alexhuszagh** [comment]
A simple way to reproduce this:

```toml
submod = { path = "../submod, version = "1.0" }
```

Relative paths work fine if they're a child of the directory, any ".." in the path causes issues.

**Comment by Dylan-DPC** [comment]
Thanks for opening the issue (and sorry about the delays) 

From the readme: 
> path dependencies (in Cargo.toml) that point outside the Cargo project won't work because cross use docker containers only mounts the Cargo project so the container doesn't have access to the rest of the filesystem.

So right now it wouldn't be possible to make this change without making a major change in how `cross` works which is beyond our scope at the moment.

**Comment by Alexhuszagh** [comment]
This was fully fixed in #684, #713, and #937.

**Comment by Alexhuszagh** [comment]
This was fully fixed in #684.
