### ISSUE TITLE
Host still requires installation of target toolchain

### ISSUE THREAD

**Issue by spease** [rust-embedded/cross#299]
There seems to be a compilation/check step that's executed in the host environment before the docker container, at least on OS X. This ends up requiring that the host actually have the target toolchain installed and working - and if I had that, I wouldn't need cross (or wouldn't need it in as many situations).

Is this intentional?

**Comment by reitermarkus** [comment]
Can you give more detail what you expect to happen? The Docker images don't contain the toolchain since the toolchain differs between `stable`, `beta` and `nightly` and all specific versions thereof, so we can't pre-install it in the container.

**Comment by spease** [comment]
I see - that makes sense, considering that would increase the size of the docker container. Alright, I see why that's done.

The next problem I run into (this is on OS X) is that it's looking for the mingw compiler when I specify a Windows target. So I'm getting

```
error occurred: failed to find tool. Is `x86_64-w64-mingw32-gcc` installed?
```

This is from backtrace-sys.

What's almost certainly happening is that this crate makes use of the cc crate to invoke the C compiler, which in turn is trying to invoke the mingw compiler. IIRC, this is installed in the container. However, I'm pretty sure I haven't gotten to the point where it's running the container yet.

**Comment by reitermarkus** [comment]
Have you installed `cross` from `master`?

**Comment by spease** [comment]
No, I installed via ‘cargo install’

**Comment by reitermarkus** [comment]
Then that's the problem, there hadn't been a release until five days ago. macOS support was only added recently. Install the new version using `--force`.
