### ISSUE TITLE
Can't cross-compile to some targets anymore

### ISSUE THREAD

**Issue by CryZe** [rust-embedded/cross#306]
This might be more of a question, but some of the targets that I've successfully been cross-compiling to with cross / trust on CI are now erroring like this:
```
error: cross does not provide docker image for x86_64-unknown-linux-gnux32 target, specify a custom image in Cross.toml
```
These have always worked before though, so is this a regression?

**Comment by CryZe** [comment]
What I believe is happening here is that cross sometimes didn't even need to pull the images, but now there is an error check way earlier that errors out, despite there not being a need for the image.

**Comment by CryZe** [comment]
Weirdly enough I have yet to figure out the exact pattern for this. Because somehow cross can still cross-compile to wasm32-unknown-unknown even though there is no docker image. But for others it can't?

**Comment by reitermarkus** [comment]
Yeah, `is_supported` should check if the host supports compiling the target natively, or alternatively `needs_docker` should take the host into consideration.

**Comment by CryZe** [comment]
So how do I work around this? Clearly not all linux targets need docker (or something?) but the error appears anyway.

**Comment by reitermarkus** [comment]
> So how do I work around this?

There's no workaround, but this is definitely a bug which needs to be fixed.

**Comment by CryZe** [comment]
I believe this is maybe because I'm cross compiling as static and shared libraries, so maybe the actual specific linker for the platform (and thus the whole docker image) isn't necessary?

**Comment by reitermarkus** [comment]
Which targets apart from `x86_64-unknown-linux-gnux32` are failing?

**Comment by CryZe** [comment]
I'm currently doing a clean CI run atm (there were other issues mixed in in my previous run, such as Travis CI having spurious timeouts and some other compilation bug I caused). I'll respond with a full list of targets that are now rejected soon.

**Comment by CryZe** [comment]
Alright so here are all the failures: https://travis-ci.org/LiveSplit/livesplit-core

 - x86_64-unknown-linux-gnux32 (Fixed in #308)
 - armv5te-unknown-linux-gnueabi (does not provide docker image)
 - powerpc64le-unknown-linux-gnu (Fixed in #307)
 - i686-unknown-freebsd (Unable to find image)
 - x86_64-unknown-freebsd (Unable to find image)
 - asmjs-unknown-emscripten (Unable to find image)

Interestingly wasm32-unknown-emscripten actually got fixed by the latest cross.

**Comment by kurojishi** [comment]
+1 we are hitting the same issue with:

https://travis-ci.org/awslabs/flowgger/builds/581609924

i686-unknown-freebsd (Unable to find image)
x86_64-unknown-freebsd (Unable to find image)

**Comment by reitermarkus** [comment]
I'm not sure a `armv5te-unknown-linux-gnueabi` image ever existed, so no idea how this was working before.

For the other images which are missing: These were disabled because they don't build anymore and no-one has bothered to fix them. So you can either drop support for them too or send a PR to fix them.

**Comment by CryZe** [comment]
Yeah that's why I was saying that I don't think I even need the proper linkers to build for these targets as I only build static and shared libraries (which maybe cargo doesn't need a linker for?). I'm not entirely sure. But it definitely worked before.

Pretty sure the asmjs target should work if the wasm32-emscripten one does. So I bet that's just a matter of activating it on cross' side again. I'm fine with dropping the armv5te target, not sure about the freebsd ones, but I could temporarily drop them too.

**Comment by vishaltelangre** [comment]
Facing similar issue. Failing to compile for following targets.

- powerpc64le-unknown-linux-gnu
- i686-unknown-freebsd
- x86_64-unknown-freebsd

The debug information/log is available at https://travis-ci.org/vishaltelangre/ff/builds/581675207 for these targets.

**Comment by kurojishi** [comment]
The README still lists them:

https://github.com/rust-embedded/cross/blob/master/README.md

We are dropping the freebsd targets too

**Comment by CryZe** [comment]
@reitermarkus Do you know what supposedly is wrong with asmjs-unknown-emscripten? Cause I can't think of a reason why it should be disabled.

**Comment by reitermarkus** [comment]
It was disabled in https://github.com/rust-embedded/cross/pull/231, probably because of https://travis-ci.org/rust-embedded/cross/builds/455974395.

**Comment by CryZe** [comment]
Yes, but the intention with https://github.com/rust-embedded/cross/pull/230 was to enable them again. And considering the wasm one works again and is part of 0.1.15, the asmjs one should work just fine. I assume you thought the PR was only for wasm or something, so it should still be disabled despite it likely working again since the PR is for both.

**Comment by reitermarkus** [comment]
> the intention with https://github.com/rust-embedded/cross/pull/230 was to enable them again

Yep, and no one has bothered to to that as of yet.

> so only wasm was enabled again

The `wasm` one was never completely disabled but pinned to a very old nightly Rust. Arguably it should be disabled since the `CPP` and `RUN` tests are disabled. The same is probably true for `asmjs`.

**Comment by CryZe** [comment]
Is there a plan for a 0.1.16 soon (or I guess 0.1.15.1 if that's a thing) with the fixes? (asmjs missing, ppc64le test runner broken, too new qemu for some tests, incompatibility with GitHub Actions, ...)
