### ISSUE TITLE
i cant seem to find the compiled binary anywhere. Where is the binary located? 

### ISSUE THREAD

**Issue by NikosEfthias** [rust-embedded/cross#311]

**Comment by reitermarkus** [comment]
Please provide a better description of your issue.

**Comment by NikosEfthias** [comment]
i ran `cross build  --target x84_64-uknown-linux-musl` in my project and the compilation was successful.
After that, I went into the `target/x86...musl/debug`  folder there were folders like `native,build` etc but there was no binary located anywhere around which I can ship or run

**Comment by reitermarkus** [comment]
I cannot reproduce this.
