### ISSUE TITLE
Cross v0.1.15 Breaks f64 Modulus on i686

### ISSUE THREAD

**Issue by Alexhuszagh** [rust-embedded/cross#314]
The following code worked for cross v0.1.14, so any issues were introduced with the latest release.

# Targets

- i686-unknown-linux-gnu

x86_64 works fine, so the issue only occurs on 32-bit x86.

# Failing Code

```rust
fn main() {
    let value: f64 = 29860476080414620.0;
    let base: f64 = 17.0;
    println!("value % base = {:?}", value % base);
}
```

# Results

```bash
value % base = -4.0
```

The value is negative for the float modulus, rather than `15.0`.  Running with target `x86_64-unknown-linux-gnu` prints the expected result (`15.0`).

# Minimal Steps to Reproduce

1. Create a repository (`cargo new --bin sample`).
2. Copy the failing code into `main.rs`.
3. Run the binary on i686 (`cross run --target i686-unknown-linux-gnu`).

Finally, this code works with `cargo run --target i686-unknown-linux-gnu`.

**Comment by Alexhuszagh** [comment]
Update: Running the generated binary without qemu produces the desired result, while running it with Qemu fails. This seems to be a bug in Qemu.

```
$ uname -a
Linux ahuszagh.localdomain 5.2.7-100.fc29.x86_64 #1 SMP Thu Aug 8 05:30:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ qemu-i386 --version
qemu-i386 version 3.0.1 (qemu-3.0.1-4.fc29)
cross --version
cross 0.1.15
cargo 1.37.0 (9edd08916 2019-08-02)
$ target/i686-unknown-linux-gnu/debug/sample
value % base = 15.0
$ qemu-i386 target/i686-unknown-linux-gnu/debug/sample
value % base = -4.0
```

Compiling the binary with an older version of cross (v0.1.14) and then executing it with a newer version of Qemu fails:

```bash
$ qemu-i386 --version
qemu-i386 version 3.0.1 (qemu-3.0.1-4.fc29)
$ cross --version
cross 0.1.14
cargo 1.37.0 (9edd08916 2019-08-02)
$ cross build --target i686-unknown-linux-gnu
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
$ target/i686-unknown-linux-gnu/debug/sample
value % base = 15.0
$ qemu-i386 target/i686-unknown-linux-gnu/debug/sample
value % base = -4.0
```

**Comment by Alexhuszagh** [comment]
Confirmed a Qemu bug. Will file upstream.

# Source

**a.c**
```c
#include <math.h>
#include <stdio.h>

int main()
{
    double x = 29860476080414620.0;
    double y = 17.0;
    double z = fmod(x, y);
    printf("%f\n", z);
    return 0;
}
```

# Compile Command

```bash
$ gcc --version
gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
$ gcc a.c -o a -m32 -lm
```

# Calling

```bash
$ ./a 
15.000000
$ qemu-i386 a
-4.000000
```

**Comment by Alexhuszagh** [comment]
@reitermarkus This is a separate issue from #314.

First, cross v0.1.14 did not use qemu for i686. No version of qemu works, on i686 (really the i387, since this is all going to be done by the FPU), to my understanding. I've tested 2.10.0, 3.0.1, 4.1.0, and the latest [commit](https://git.qemu.org/?p=qemu.git;a=commit;h=90b1e3afd33226b6078fec6d77a18373712a975c) as of testing.

I've filed the bug upstream, and is available here:
https://bugs.launchpad.net/qemu/+bug/1843205

As the bug is upstream, and no working versions of qemu seem to exist, I'm not sure if there's anything cross should do, since the alternative is the i686 target only works on x86.

**Comment by reitermarkus** [comment]
So it should work running natively inside the Docker container?

**Comment by Alexhuszagh** [comment]
Yes, on x86 or x86_64. In practice, I doubt anyone will be running cross on anything other than x86 or ARM.

**Comment by Alexhuszagh** [comment]
We could check `uname -m`, and if the value is `i386`, `i486`, `i586`, `i686`, or `x86_64`, then just run the binary natively.

**Comment by reitermarkus** [comment]
Non-x86 hosts aren't supported at the moment, and I doubt there is any demand for it, so this should be fine.

Look at the `linux-runner` script, we can make `CROSS_RUNNER` default to `native` with the `uname` check, otherwise to `qemu-user`.

**Comment by Alexhuszagh** [comment]
Would something like this work? If we're assuming the host is x86, then we don't need to check the machine hardware name: every host should be able to run an i686 binary (this bug doesn't occur for x86_64).

```diff
diff --git a/docker/linux-runner b/docker/linux-runner
index 9e1e1e7..1d58759 100755
--- a/docker/linux-runner
+++ b/docker/linux-runner
@@ -14,7 +14,14 @@ arch=$1
 shift
 
 if [ "$CROSS_RUNNER" = "" ]; then
-    CROSS_RUNNER=qemu-user
+    if [ "$arch" = i686 ]; then
+        # override 32-bit x86 targets to run natively (assume host is x86).
+        # workaround for upstream issue in qemu for the i386 target
+        # https://bugs.launchpad.net/qemu/+bug/1843205
+        CROSS_RUNNER=native
+    else
+        CROSS_RUNNER=qemu-user
+    fi
 fi
 
 # select qemu arch
```

**Comment by reitermarkus** [comment]
Yes, I think that should work. I think we should default to `native` on all targets where this is possible.
