### ISSUE TITLE
Error when compiling from linux to windows

### ISSUE THREAD

**Issue by Tigralt** [rust-embedded/cross#336]
Hello,
I get an error whenever I am trying to compile to **x86_64-pc-windows-gnu**.
I'm trying to compile a Rust code thanks to TravisCI and I'm running cross from **Ubuntu bionic**. I tried with cross v0.1.16 and the master version but I still get the error:

> note: x86_64-w64-mingw32-gcc: error: crt2.o: No such file or directory
>          x86_64-w64-mingw32-gcc: error: rsbegin.o: No such file or directory
>          x86_64-w64-mingw32-gcc: error: rsend.o: No such file or directory

I have well installed **mingw-w64** and also added the **x86_64-w64-mingw32-gcc** linker in *~/.cargo/config*.
Any idea how to resolve this?

**Comment by CryZe** [comment]
The windows gnu nightly is currently broken in general. This has nothing to do with cross.

**Comment by Tigralt** [comment]
Ok my bad, I thought it was a problem with some linker in cross docker. Closing this issue.
