### ISSUE TITLE
Official support for podman

### ISSUE THREAD

**Issue by oblitum** [rust-embedded/cross#337]
I thought it would be worth to have an issue for this.

I think podman is the simplest solution for running containers rootless, daemonless and safely (without being part of high privileged user groups), and it [can be made to work](https://github.com/rust-embedded/cross/issues/298#issuecomment-542432899).

related issues: #185, #298

**Comment by reitermarkus** [comment]
No objections to that. Can you submit a PR?

**Comment by oblitum** [comment]
Maybe, but at some random later point in time. I'll have to check the codebase to assess whether I have knowhow for this.

**Comment by reitermarkus** [comment]
Implemented in https://github.com/rust-embedded/cross/pull/344.

**Comment by oblitum** [comment]
Nice!
