### ISSUE TITLE
Cross compiling mozilla firefox browser

### ISSUE THREAD

**Issue by jefflancaster** [rust-embedded/cross#341]
Using the mozilla-central latest release and doing:

cargo build --target=mips-unknown-linux-musl

I get the following error:
   Compiling crc32fast v1.2.0
   Compiling indexmap v1.1.0
   Compiling static_prefs v0.1.0 (/project/modules/libpref/init/static_prefs)
error: environment variable `MOZ_TOPOBJDIR` not defined
  --> modules/libpref/init/static_prefs/src/lib.rs:11:18
   |
11 | include!(concat!(env!("MOZ_TOPOBJDIR"), "/modules/libpref/static_prefs.rs"));
   |                  ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `static_prefs`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by reitermarkus** [comment]
See https://github.com/rust-embedded/cross#passing-environment-variables-into-the-build-environment.
