### ISSUE TITLE
"--locked" flag ignored in "cross build"

### ISSUE THREAD

**Issue by RalfJung** [rust-embedded/cross#346]
In https://github.com/japaric/xargo/pull/264 I am trying to ensure that xargo's lockfile is up-to-date on CI, so I added `--locked` to our `cross build` invocation. However, that seems to have no effect: even with a stale lockfile, and even with no lockfile at all, the build succeeds!

Silently ignoring important CLI flags like that seems quite surprising, so I was wondering if this is deliberate and if there's any way to do a locked build here.

**Comment by reitermarkus** [comment]
Not sure why it would do that. All flags are passed through to `cargo` in the container. You can check that with the `--verbose` flag.

**Comment by RalfJung** [comment]
Maybe something runs `cargo update` or some similar command first that would result in the lockfile not being any more the original one?

**Comment by reitermarkus** [comment]
Ok, so it seems obvious that this must be the culprit:

https://github.com/rust-embedded/cross/blob/ea29a50d236bd5bda5b9eb14ab04dedb46c96d96/src/docker.rs#L101-L108

**Comment by RalfJung** [comment]
Yes. That one should likely also have `--locked` when that flag is set for the main command.
