### ISSUE TITLE
Wishlist: Add curl binary to docker images

### ISSUE THREAD

**Issue by alekseysidorov** [rust-embedded/cross#350]
A lot of packages use `curl` to fetch their dependencies. For example with the default cross images I can't compile `exonum_libsodium-sys` due to error:

thread 'main' panicked at 'Failed to run curl command: No such file or directory (os error 2)', /cargo/registry/src/github.com-1ecc6299db9ec823/exonum_libsodium-sys-0.0.23/build.rs:88:17

**Comment by reitermarkus** [comment]
Feel free to add it.
