### ISSUE TITLE
/cargo/bin not found

### ISSUE THREAD

**Issue by sify21** [rust-embedded/cross#364]
## Version
cross 0.2.0-alpha.1 (2f284ac 2020-01-09)
cargo 1.40.0 (bc8e4c8be 2019-11-22)
podman version 1.6.2
## Error
run `cross build --release --target x86_64-unknown-linux-musl`, image is downloaded by podman, error info is:
```
Error: error checking path "/cargo/bin": stat /cargo/bin: no such file or directory
```

**Comment by reitermarkus** [comment]
Look at https://github.com/rust-embedded/cross#dependencies. Podman 1.6.3 or higher is required.

**Comment by sify21** [comment]
Thank you @reitermarkus , didn't notice
