### ISSUE TITLE
Release v0.2.0 seems to be missing the MUSL binary

### ISSUE THREAD

**Issue by Byron** [rust-embedded/cross#379]
This is breaking my build.
https://travis-ci.org/Byron/dua-cli/jobs/653944394#L465

Do you think it's possible to force an older version for the time being?
Thanks for your advise, it's much appreciated.

**Comment by reitermarkus** [comment]
It's definitely available from the releases page now: https://github.com/rust-embedded/cross/releases/tag/v0.2.0

**Comment by Byron** [comment]
Thanks! 
Indeed, it's there now and retriggering the pipeline was all it took.

What confused me is that the commit creating the release apparently was 6 hours old, which was about the time when my pipeline failed.

Is there any learning from this, @reitermarkus? Or is there anything I should consider to do or not do in future to prevent this from happening again? Thank you.

**Comment by reitermarkus** [comment]
I think the problem is that the tag/release is created before the artifacts are uploaded. Not sure what the best workflow would be so that doesn't happen.
