### ISSUE TITLE
Update to buster?

### ISSUE THREAD

**Issue by MGlolenstine** [rust-embedded/cross#380]
I need to build `druid` crate, but it requires `gtk+ >= 3.20`, but the highest that can be installed into stretch is `3.18.9`. Is there a way to update the QEMU machine to buster?

**Comment by MGlolenstine** [comment]
I've updated it manually for the time being. What I did, was cloned the repository and changed the wanted `Dockerfile` to start with `FROM ubuntu:18:04`.

**Comment by Bram-Boris** [comment]
Hi @MGlolenstine, I see you are also trying to use a GUI on an embedded device. So far I have not had any success compiling libraries like Iced, Azul, Druid etc due to linker errors or just not compiling at all. But it looks like you got it working using Cross! Could you share your custom docker file/packages that you used?

**Comment by MGlolenstine** [comment]
@Bram-Boris

Correct, I got it working on almost all of those (Druid, Azul, Relm, Iced and Neutrino), but had some problems running all of those, not because of linker errors, but unexplained panics. But all of them, except Neutrino, did provide a working executable for my platform (armhf 32bit).

Here are some things I found out (but keep in mind,  that this is biased on our project, as we need a touchscreen):
```
Druid:
    - No touch support for scrolling (listviews)
    - Title bar always shown (we could fix this one, but it would require OpenBox configuration and because other libs support it's removal I'm putting this here)
Azul:
    - No CSS support (it looks like it doesn't load)
    - Panics if there's no mouse or keyboard connected to the device (we only have a touchscreen)
Relm:
    - Everything works without a problem (we're gonna be sticking to this one for now)
Iced:
    - Panic at the start
Neutrino
    - Doesn't build for armhf (32bit)

```

I got it working by changing the `FROM ubuntu:16.04` to `FROM ubuntu:18.04` and compiling it, as mentioned above. Then I created my custom `Dockerfile` and installed libraries, that were needed for the compilation
```
FROM rustembedded/cross:armv7-unknown-linux-gnueabihf
RUN dpkg --add-architecture armhf && apt-get update && apt-get install -y libglib2.0-dev:armhf \
libcairo2-dev:armhf \
libatk1.0-dev:armhf \
libpango1.0-dev:armhf \
libgdk-pixbuf2.0-dev:armhf \
libgtk-3-dev:armhf \
libsoup2.4-dev:armhf \
libwebkit2gtk-4.0-dev:armhf
ENV PKG_CONFIG_ALLOW_CROSS=1
ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/share/pkgconfig/
ENV PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/share/pkgconfig/
```
I'm unsure if the last two lines do anything, but I've put them there just to be sure, and as the compilation takes about 10min on my computer, I really didn't want to test it out.

I just want to add, that if you want to use this in the README, feel free to do so, as the current README doesn't really explain well on how to do these custom `Docker` images.

I hope I gave you some insightful information :)

**Comment by Bram-Boris** [comment]
@MGlolenstine Woah, this is very nice! I'm gonna try this somewhere tonight and will report back!
