### ISSUE TITLE
Automatically define PKG_CONFIG_ALLOW_CROSS 

### ISSUE THREAD

**Issue by gdesmott** [rust-embedded/cross#383]
Various crates requires env variable `PKG_CONFIG_ALLOW_CROSS` to be defined when being cross-compiled. Maybe `cross` should automatically set it to ease users' experience?

**Comment by reitermarkus** [comment]
@gdesmott, can you submit a PR for this? Thanks!

**Comment by gdesmott** [comment]
@reitermarkus : here we go: https://github.com/rust-embedded/cross/pull/386
