### ISSUE TITLE
Cross-compile for Raspberry Pi Zero W produces segmentation fault

### ISSUE THREAD

**Issue by Darneas** [rust-embedded/cross#391]
I have the minimal Rust hello world example and use `cross` to compile it for `arm-unknown-linux-gnueabihf`:

`cross build --release --target=arm-unknown-linux-gnueabihf`

When I deploy the file to the Pi Zero W, it produces a segmentation fault.

I have a working cross-compilation setup using [this other toolchain repo](https://github.com/Pro/raspi-toolchain) but I would really love to use `cross` instead. What I read there was that  GCC versions before GCC8 would produce bad binaries for the Raspi. This is also confirmed by that fact that I tried various other toolchains, but only few worked.

Could we maybe update [the related Dockerfile](https://github.com/rust-embedded/cross/blob/master/docker/Dockerfile.arm-unknown-linux-gnueabihf) accordingly and use a newer GCC? I saw that the linaro repo unfortunately does not provide it yet but instead they are now hosted by ARM themselves.

I would be happy to create a pull-request for this, but need a bit of guidance to make it fit into the overall `cross` project.

**Comment by bootrino** [comment]
What is the process to be able to make use of this update?

I'm trying to compile for Raspberry Pi and also getting a segmentation fault.

thanks

**Comment by Darneas** [comment]
For some reason, `cross` by default uses the tag `0.2.0` and not `latest`. #392 only led to an update of the `latest` Docker image.

Try adding the following `Cross.toml` file to force it to use the latest version (and consider doing a manual `docker pull` for the image if the problem persists):

```toml
[target.arm-unknown-linux-gnueabihf]
image = "rustembedded/cross:arm-unknown-linux-gnueabihf"
```

**Comment by bootrino** [comment]
Hello thanks for your reply where should I place the Cross.toml file?

Regarding the tag, will this be fixed in a future release?

thanks

**Comment by Darneas** [comment]
> Hello thanks for your reply where should I place the Cross.toml file?

At the same level as your `Cargo.toml`. See [README](https://github.com/rust-embedded/cross#configuration).

**Comment by hombit** [comment]
> ```toml
> [target.arm-unknown-linux-gnueabihf]
> image = "rustembedded/cross:arm-unknown-linux-gnueabihf"
> ```

@Darneas Somehow `cross` ignores this and uses `rustembedded/cross:arm-unknown-linux-gnueabihf-0.2.0` image

**Comment by Darneas** [comment]
The `Cross.toml` should contain the two lines. The file should be at the same level as the `Cargo.toml`.

**Comment by talksik** [comment]
for newer folks here, I was able to use `arm-unknown-linux-gnueabihf` as the target instead of `armv7-unknown-linux-gnueabihf`. README for this repo has a table of available targets. Turns out the pi zero has armv6 so armv7 doesn't work.
