### ISSUE TITLE
*BSD support?

### ISSUE THREAD

**Issue by carllerche** [rust-embedded/cross#40]
Hey, great work.

I was wondering if it is possible to support the various *BSDs as part of the platforms? I've definitely had issues with Mio breakage.

**Comment by japaric** [comment]
`cross build` for *BSD shouldn't be too hard to implement. It's possible to cross compile to those targets from Linux and the instructions to build the cross compilers are [here](https://github.com/rust-lang/rust-buildbot/tree/master/slaves/linux-cross)

`cross test` would be much more complicated to implement and, I expect, very slow. It would require spinning up a QEMU VM per "test runner". (one for every file in the `tests` directory)

**Comment by carllerche** [comment]
I do believe that the libc crate does use qemu to get freebsd testing: https://github.com/rust-lang/libc/tree/master/ci

It definitely wouldn't be fast...

**Comment by japaric** [comment]
Yeah, I'm aware of how libc tests the *bsd targets. The tricky part is doing something like that *transparently* when `cross test` is used.

> It would require spinning up a QEMU VM per "test runner

I have an idea to avoid this *and* keep the command transparent but I need to think more about and then prototype it (for Linux targets, first).

**Comment by nagisa** [comment]
The failure mode is not ideal:

> error: could not execute process `/target/x86_64-unknown-freebsd/debug/deps/testexe` (never executed)

**Comment by jan-hudec** [comment]
Would the new `target.`*`.runner` configuration option in cargo (https://github.com/rust-lang/cargo/pull/3954) help? It should make almost anything transparent.

**Comment by bgermann** [comment]
I would also be willing to work on this (to enable Solaris tests). I guess with such a test runner in place libc would be willing to use cross for their testing.

I would suggest the following approach to cross compile and then run the tests in Qemu:

For a `cross test --target <triple> ...` invocation with a not supported triple do the following:
1a. Run `cross test --target <triple> --no-run ...` natively.
1b. The test runner starts Qemu with a TUN/TAP device attached (hopefully this is possible with Travis CI docker containers). Error if no Qemu machine to emulate the given target triple is available.
2. The Qemu image's operating system has Cargo and a TCP service preinstalled that listens for incoming remote Cargo calls (consisting of the given command line arguments, the Cargo.toml and a tar with the compiled tests). Any suggestions for the RPC format?
3. The test runner packages the resulting target files from 1a in a tar.
4. The test runner waits for the service to become available.
5. The test runner calls the service with the ... command line arguments.
6. The service unpacks the tar and builds the appropriate directory structure with the Cargo.toml.
7. The service calls `cargo test ...`.
8. The output is sent as a RPC response.
9. The test runner outputs the RPC response.

I do not know if the Rust source is needed in this scenario. If yes, then the tar would have to contain it as well.

**Comment by Dylan-DPC** [comment]
I feel this has been resolved by multiple Prs (can't find the exact numbers) so i'm closing this. If you feel that any platform is still missing, you can open a new issue.

**Comment by bgermann** [comment]
The cross test support is not resolved at all!

**Comment by Dylan-DPC** [comment]
@gnzlbg yeah the test support isn't added yet, will create a new issue. This issue is stagnant for a long time, so better to create a new one. Thanks
