### ISSUE TITLE
Cross test command is slow

### ISSUE THREAD

**Issue by Luni-4** [rust-embedded/cross#430]
I run `cross test --target aarch64-unknown-linux-gnu` to test [rav1e](https://github.com/xiph/rav1e/) and the entire process took 44 minutes. The command was run locally on `Ubuntu 19.10` and on a `Github Action` job, but both of them took the same time.

The `cross build --target aarch64-unknown-linux-gnu` and `cross run --target aarch64-unknown-linux-gnu -- --help` instead worked perfectly. Is there any reason why the `cross test` command is so slow?

Thanks in advance for your help and feedback! :)

**Comment by svenstaro** [comment]
The reason is that your qemu uses software virtualization. I don't think there's much to be done there with foreign architectures.

**Comment by Luni-4** [comment]
Yeah, i think that is the problem. Closing now. Thanks for your help @svenstaro! :)
