### ISSUE TITLE
Passing an empty string to --features causes a panic.

### ISSUE THREAD

**Issue by eduardosm** [rust-embedded/cross#466]
Using cross 0.2.1, passing an empty string to `--features` (`cross build --features ""`) causes cross to panic:

```
thread 'main' panicked at 'byte index 1 is out of bounds of ``'
```

**Comment by sudipghimire533** [comment]
Not only `--features` but any argument (valid or not) when passed with empty quoted string `""` results in panic.

**Comment by sudipghimire533** [comment]
Attempt to solve this with #575 

My first PR ever to others repo tho :wink:
