### ISSUE TITLE
i686-pc-windows-gnu support

### ISSUE THREAD

**Issue by amircodota** [rust-embedded/cross#469]
We have a rust binary with openssl that we need to cross compile for windows - both x86_64 and i686.

I was able to create a custom docker image for x86_64-pc-windows-gnu that works well.

I also tried to create a custom image for i686-pc-windows-gnu. There was no base image to customize, so I copied the `Dockerfile.x86_64-pc-windows-gnu` file to a new one, and changed some stuff around to make it use `g++-mingw-w64-i686`.

That got me further along - openssl-sys seems to compile correctly.

However, now I get these errors:

`/rustc/c367798cfd3817ca6ae908ce675d1d99242af148\/src\libstd/backtrace.rs:229: undefined reference to _Unwind_Resume`

This seems to stem from mingw64 for i686 using sjlj for exception handling instead of dwarf-2 which the rust compiler expects (according to [this](https://github.com/rust-lang/rust/issues/12859)).

Has anyone here had success with this?

In the past, we had success with the `japaric/i686-pc-windows-gnu` docker image, so maybe @japaric can shed some light on this?

This image no longer works for me. I tried reverting to older versions of `cross` and older versions of `rust`, but it still fails.
The weird thing is that this image still works on an old ci machine machine we have, but not on my machine, and I could not figure out why.

Thanks
Amir

**Comment by japaric** [comment]
>  so maybe @japaric can shed some light on this?

I'm sorry it's been too long since I looked into that target's Dockerfile.

> This seems to stem from mingw64 for i686 using sjlj for exception handling instead of dwarf-2 which the rust compiler expects (according to this).

Different exception handling is the only thing I remember about these mingw targets.

**Comment by malbarbo** [comment]
I created a fix: https://github.com/rust-embedded/cross/pull/471

**Comment by amircodota** [comment]
Awesome news @malbarbo Thanks!

**Comment by amircodota** [comment]
@malbarbo Just tried it and it worked like a charm. Thanks!
