### ISSUE TITLE
Could NOT find OpenSSL

### ISSUE THREAD

**Issue by mlmarius** [rust-embedded/cross#474]
I want to cross compile a project from MacOS to have it run on a Raspberry 3. I am doing this:
`cross build --target armv7-unknown-linux-gnueabihf`

But I soon hit this error:
```
  fatal: Not a git repository (or any parent up to mount point /cargo)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
  CMake Error at /usr/local/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
    Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
    system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
    OPENSSL_INCLUDE_DIR)
  Call Stack (most recent call first):
    /usr/local/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
    /usr/local/share/cmake-3.5/Modules/FindOpenSSL.cmake:370 (find_package_handle_standard_args)
    src/CMakeLists.txt:186 (find_package)
```
Any hints on how to set up OpenSSL for this cross-compilation ? Doing `cargo run` from that same directory works as expected after I've set the following: `OPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1`

LATER EDIT:

I tried compiling my project on an actual Raspberry and it turns out I had to install the following packages in order to get it to compile: `cmake clang libssl-dev'. How can I make cross prepare the environment before compiling?

**Comment by Alexhuszagh** [comment]
See the [OpenSSL](https://github.com/cross-rs/cross/wiki/FAQ#openssl-is-not-installed) section of our wiki, which provides instructions for how to build projects with OpenSSL dependencies and reasons why it is not installed by default.
