### ISSUE TITLE
linker can't find -lsqlite3

### ISSUE THREAD

**Issue by gyaur** [rust-embedded/cross#479]
`arm-linux-gnueabihf/bin/ld: cannot find -lsqlite3` when running `cross build  --target armv7-unknown-linux-gnueabihf` to compile for raspberrypi.

**Comment by gyaur** [comment]
I'm using this Dockerfile:

```
FROM rustembedded/cross:armv7-unknown-linux-gnueabihf

RUN apt-get update && \
    apt-get install -y sqlite3 libsqlite3-dev

```
`docker build -t my/cross:latest .`

Cross.toml:
```
[target.armv7-unknown-linux-gnueabihf]
image = "my/cross:latest"
```

but the error persists when running `cross build  --target armv7-unknown-linux-gnueabihf`

**Comment by sinkingpoint** [comment]
Had this exact issue just now oddly enough - weird timing.

What worked for me was installing the armhf packages from apt instead of the native ones, i.e. This Dockerfile:

```
FROM rustembedded/cross:armv7-unknown-linux-gnueabihf-0.2.1

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -y libsqlite3-dev:armhf
```

(Mildly Cargo Culted from the README)

**Comment by gyaur** [comment]
Thanks that worked. I was dumb and tried it  with armv7 instead of armhf
