### ISSUE TITLE
cross run: stdin doesn't work

### ISSUE THREAD

**Issue by japaric** [rust-embedded/cross#52]
```
$ echo hello | cross run
the input device is not a TTY
```

**Comment by timvisee** [comment]
I'm having the same issue when running `cross` on GitLab CI, probably because the CI doesn't _emulate_ a full tty.

Would it be possible to disable the use of  `-t` when `cross` is calling Docker internally (of which I think it is causing the issue)?

**Comment by xoac** [comment]
Similar issue for Azure Pipelines.
[example error](https://dev.azure.com/sylwesterrapala/azure-piplines/_build/results?buildId=43&view=logs&jobId=312f514c-a13c-5002-5c1c-5965933fa245&taskId=4b774352-b315-57f2-6e3f-d4308a83a5b7&lineStart=15&lineEnd=16&colStart=1&colEnd=1)

**Comment by xoac** [comment]
@borsboom temporary solution for azure pipelines [here](https://github.com/xoac/rust-azure-pipelines/blob/684c2e07008bdd58ace2642dededa694a1319c8b/ci/cargo-cross.yml#L12-L22) I think similar can be done for gitlab.

**Comment by ndusart** [comment]
shouldn't it be closed by #294 ?

**Comment by reitermarkus** [comment]
Yes, this should be fixed.
