### ISSUE TITLE
Where can I find documentation for cross.toml?

### ISSUE THREAD

**Issue by wpd** [rust-embedded/cross#529]
Specifically, I am wondering if it is possible to specify the target in the cross.toml (or even the cargo.toml) file.

Thank you.

(Aside... I wish that there were a "Discussions" section to this project rather than just "Issues"... I would have submitted this as a discussion question rather than an issue if that had been an option to me.)

--wpd

**Comment by Dylan-DPC** [comment]
> (Aside... I wish that there were a "Discussions" section to this project rather than just "Issues"... I would have submitted this as a discussion question rather than an issue if that had been an option to me.)

Opened up discussions for this repo now. Go ahead and be the first ;)

**Comment by wpd** [comment]
Thank you .  That addressed my "issue" :-)

**Comment by Alexhuszagh** [comment]
We now have extension documentation on cross [configuration](https://github.com/cross-rs/cross/wiki/Configuration).
