### ISSUE TITLE
Must provide PYO3_CROSS_LIB_DIR environment variable

### ISSUE THREAD

**Issue by jdaruja** [rust-embedded/cross#556]
Have set environment variable "PYO3_CROSS_LIB_DIR" using export PYO3_CROSS_LIB_DIR = "/usr/lib"
But getting below error.

  Error: "Must provide PYO3_CROSS_LIB_DIR environment variable when cross-compiling"

**Comment by mfaccin** [comment]
hi, did you solve this issue @jdaruja ?

**Comment by jdaruja** [comment]
No, so i dropped it

**Comment by Emilgardis** [comment]
cross doesn't pass environment variables by default. See https://github.com/rust-embedded/cross#passing-environment-variables-into-the-build-environment

**Comment by jdaruja** [comment]
Thank you very much for the link. Its  working

**Comment by mfaccin** [comment]
hey @Emilgardis @jdaruja sorry for the noob question. I'm trying to cross-compile to an aarch64 architecture, how can I get the already compiled versions or the files that I should point to?

**Comment by Alexhuszagh** [comment]
@mfaccin That's unrelated to the issue at hand: please open a discussion. Note that you can use custom Dockerfiles which support copying local files in the current context over to the image.
