### ISSUE TITLE
Cross uses host cargo config.toml

### ISSUE THREAD

**Issue by DizzyWasTaken** [rust-embedded/cross#622]
Hello,

I'm building with cross using a custom docker image and it uses my host `.cargo/config.toml` parameters. In particular
```
[build]
rustc-wrapper = "sccache"
```
which makes every attempt at building fail.

I was under the impression that the rust environment cross uses was the one that's on the docker image. Is there a way of making it ignore my host's cargo config?

**Comment by Emilgardis** [comment]
Duplicate of #621

**Comment by DizzyWasTaken** [comment]
Oops, didn't notice. Thanks for the notice.
