### ISSUE TITLE
Cross doesn't have a nice way to set RUST_BACKTRACE

### ISSUE THREAD

**Issue by Arzte** [rust-embedded/cross#74]
Currently you have to run the command with ``RUST_BACKTRACE=1``. This could possibly be a set flag/config setting for cross for debug.

**Comment by japaric** [comment]
Cross sets some variables in the Docker container to tell Cargo which linker / C compiler to use so we can't just pass the whole outer environment to the Docker container as that could break Cross.

Perhaps we could have a configurable whitelist in Cross.toml for this purpose. I don't really want to hardcode a whitelist in Cross itself.

**Comment by SirDoctors** [comment]
That sounds like a good idea, would make it easier when trying to diagnose problems

**Comment by Susurrus** [comment]
This should be resolved by #91 I think. @SirDoctors Can you check?

**Comment by malbarbo** [comment]
@Dylan-DPC I think this can be closed per @Susurrus comment.

**Comment by Dylan-DPC** [comment]
assumed resolved by #91

**Comment by Alexhuszagh** [comment]
This is now done automatically in #1073.
