### ISSUE TITLE
Refactor `Target` to separate out triple components?

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-embedded/cross#95]
@japaric would you be open to a refactor of `Target` break things up a bit. I'm thinking something like what appears in the [LLVM source](http://llvm.org/docs/doxygen/html/Triple_8h_source.html). This would allow `is_bsd()` to be reduced to:

```rust
fn is_bsd(&self) -> bool {
    match self.os {
        FreeBsd | NetBsd | Dragonfly | OpenBsd => true,
        _ => false
    }
```

and other similar simplifications. The outline I'm imagining is this:

```rust
pub struct Triple {
    arch: Arch,
    sub_arch: Option<SubArch>,
    vendor: Vendor,
    os: Os,
    environment: Environment,
}

pub enum Arch {
    X86,
    X86_64,
    /* ... */
}

// Mosty for ARM.
pub enum SubArch {
    ArmV7,
    /* ... */  // Not actually that many for the purposes of cross
}

pub enum Vendor {
    Unknown,
    Apple,
    Pc,
    /* ... */
}

pub enum Os {
    Linux,
    Darwin,
    Windows,
    /* ... */
}

pub enum Environment {
    Gnu,
    GnuEabi,
    GnuEabiHf,
    Musl,
    /* ... */
}

**Comment by japaric** [comment]
Sounds good to me! Although I'm not sure how would this support custom targets since they are free forms and may not be a triple (e.g. `foo` is a valid custom target name). Perhaps we should not try to parse those.

**Comment by Emilgardis** [comment]
@japaric 
Should be good, if it is later decided to parse custom targets, it would be easy to make a `enum Target { Triple{...}, Custom(&str)}`. If a target spec is not recognized, i.e deserializing fails with Err, we can just skip whatever setup needs to be done for targets.

**Comment by jamesmunns** [comment]
@kamalmarhubi are you still planning on working on this?

**Comment by malbarbo** [comment]
https://github.com/rust-embedded/cross/pull/217 simplified the Target enum removing hard coded targets. I think this is not relevant any more.
