### ISSUE TITLE
Add x86_64 and i686 manylinux1 targets

### ISSUE THREAD

**Issue by urschrei** [rust-embedded/cross#99]
The Python Wheel format requires Linux wheels containing compiled binaries to be built using particular versions of glibc, libstdc++ etc, on a CentOS 5.11 distro, specified in [PEP 513](https://www.python.org/dev/peps/pep-0513/) to ensure wide compatibility. x86_64 and i686 Docker images to do this are available and maintained by the community, and installing rustup and building libs works fine, but it's an extra step, requiring modifications to a `trust` setup in order to pull the docker image, install rustup, copy the binaries etc.
Would it be possible for `cross` to provide these images as targets? I'm happy to work on the PR if you're open to it.

**Comment by jamesmunns** [comment]
@urschrei, yep, you can add targets to the `docker/` folder. Let me know if you would like help!

**Comment by urschrei** [comment]
(Hi James!)
I've found two existing `manylinux1` Dockerfiles that will probably be suitable (one's maintained by [Google](https://github.com/google/or-tools/blob/master/tools/docker/manylinux1.Dockerfile), and looks pretty sensible). Is there a guide for customising a Dockerfile for `cross`, and testing? Once I'm a bit further along, I'm happy to open a PR and we can go from there.

**Comment by cschneid** [comment]
I also have need of this to support CentOS 7 and Amazon Linux 1 operating systems which run old glibc versions.

Is there any documentation of what a docker expects and the process of making one that works with cross?

**Comment by urschrei** [comment]
I got this working very easily using a custom Docker image: https://github.com/urschrei/minimal_cross_manylinux
